{{- $ca := genCA "foo-ca" 5 -}}
{{- $cert := genSignedCert "vault" (list "127.0.0.1") (list .Values.serviceName (printf "%s.%s" .Values.serviceName .Release.Namespace) (printf "%s.%s.svc" .Values.serviceName .Release.Namespace) (printf "%s.%s.svc.cluster.local" .Values.serviceName .Release.Namespace) (printf "*.%s" .Values.serviceNameInternal) (printf "*.%s.%s" .Values.serviceNameInternal .Release.Namespace) (printf "*.%s.%s.svc" .Values.serviceNameInternal .Release.Namespace) (printf "*.%s.%s.svc.cluster.local" .Values.serviceNameInternal .Release.Namespace)) 3 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vault-tls.name" . }}
  labels:
    {{- include "vault-tls.labels" . | nindent 4 }}
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
