{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vault-autounseal-operator.fullname" . }}
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [ "" ] # "" indicates the core API group
    resources: [ "secrets" ]
    verbs: [ "get", "watch", "list", "create", "update" ]
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - create
      - delete
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault-autounseal-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault-autounseal-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "vault-autounseal-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
