on:
  push:
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
      

name: Build, test and release
jobs:
  trivy-scan:
    uses: ./.github/workflows/trivy.yml
  test:
    uses: ./.github/workflows/test.yml      
  release:
    needs:
      - trivy-scan
      - test
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    outputs:
      docker_images: ${{ steps.docker_images.outputs.docker_images }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: './go.mod'
          cache: true
        id: go

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          distribution: goreleaser
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: set docker_images
        id: docker_images
        run: |
          set -eux
          DOCKER_IMAGES=`jq -r -c '[.[] | select(.type=="Docker Image") | .name]' dist/artifacts.json`
          echo "docker_images=$DOCKER_IMAGES" >> "$GITHUB_OUTPUT"

  scan-images:
    name: "scan images with trivy"
    needs:
    - release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        docker_image: ${{ fromJSON(needs.release.outputs.docker_images ) }}
    steps:
      - name: Run Trivy vulnerability scanner in repo mode - non schedule & non master
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ matrix.docker_image }}
          scan-type: 'image'
          ignore-unfixed: true # we want to have full report
          severity: 'CRITICAL,HIGH' #report all severities
          exit-code: '1'

  chainsaw-e2e-snapshot:
    uses: ./.github/workflows/chainsaw-test.yaml
    needs:
      - release
    strategy:
      matrix:
        IMAGE_TAG: ${{ fromJSON(needs.release.outputs.docker_images ) }}
