name: build
on:
  push:
    branches:
      - "master"
      - "main"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 7 * * 6'

jobs:
  trivy-scan-and-report:
    name: Trivy vulnerability scanner & rport
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Trivy vulnerability scanner in repo mode - schedule & master
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          #ignore-unfixed: true # we want to have full report
          format: 'sarif'
          output: 'trivy-results.sarif'
          #severity: 'CRITICAL,HIGH' #report all severities
          exit-code: '0'
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,ghcr.io/aquasecurity/trivy-db
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db,ghcr.io/aquasecurity/trivy-java-db
          # Not 100% sure if these are required, but so far no issues.
          TRIVY_USERNAME: ${{ github.actor }}
          TRIVY_PASSWORD: ${{ github.token }}

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
